# api 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-api
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- include "dify.global.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      {{- with .Values.api.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
        {{- include "dify.global.labels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ coalesce .Values.api.image.tag .Values.global.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: MODE
              value: "api"
            {{- include "dify.commonEnvs" . | nindent 12 }}
            {{- include "dify.commonBackendEnvs" . | nindent 12 }}
            {{- with .Values.global.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.global.extraBackendEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.api.envs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: CODE_EXECUTION_ENDPOINT
              value: "http://{{ include "dify.fullname" . }}-sandbox"
            - name: CODE_EXECUTION_API_KEY
            {{- if .Values.sandbox.apiKeySecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sandbox.apiKeySecret }}
                  key: sandbox-api-key
            {{- else if .Values.sandbox.apiKey }}
              value: {{ .Values.sandbox.apiKey | quote }}
            {{- else }}
            {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

# worker 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-worker
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
    {{- include "dify.global.labels" . | nindent 4 }}
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- include "dify.global.labels" . | nindent 8 }}
    spec:
      {{- with .Values.worker.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.worker.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.worker.securityContext | nindent 12 }}
          image: "{{ .Values.worker.image.repository }}:{{ coalesce .Values.worker.image.tag .Values.global.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          args:
          - worker
          env:
            - name: MODE
              value: "worker"
            {{- include "dify.commonEnvs" . | nindent 12 }}
            {{- include "dify.commonBackendEnvs" . | nindent 12 }}
            {{- with .Values.global.extraEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.global.extraBackendEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.worker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.worker.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

# frontend 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-frontend
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
    {{- include "dify.global.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- include "dify.global.labels" . | nindent 8 }}
    spec:
      {{- with .Values.frontend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ coalesce .Values.frontend.image.tag .Values.global.image.tag .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
          {{- include "dify.commonEnvs" . | nindent 12 }}
          {{- with .Values.global.extraEnvs }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.envs }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          {{- with .Values.frontend.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.readinessProbe}}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


# sandbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dify.fullname" . }}-sandbox
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox
    {{- include "dify.global.labels" . | nindent 4 }}
spec:
  {{- if not .Values.sandbox.autoscaling.enabled }}
  replicas: {{ .Values.sandbox.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dify.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sandbox
  template:
    metadata:
      {{- with .Values.sandbox.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dify.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sandbox
        {{- include "dify.global.labels" . | nindent 8 }}
    spec:
      {{- with .Values.sandbox.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dify.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.sandbox.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.sandbox.securityContext | nindent 12 }}
          image: "{{ .Values.sandbox.image.repository }}:{{ .Values.sandbox.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.sandbox.image.pullPolicy }}
          env:
          - name: PLACEHOLDER
            value: "PLACEHOLDER"
          {{- with .Values.sandbox.envs }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          - name: API_KEY
          {{- if .Values.sandbox.apiKeySecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.sandbox.apiKeySecret }}
                key: sandbox-api-key
          {{- else if .Values.sandbox.apiKey }}
            value: {{ .Values.sandbox.apiKey | quote }}
          {{- else }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /dependencies
          ports:
            - name: http
              containerPort: {{ .Values.sandbox.containerPort }}
              protocol: TCP
          {{- with .Values.sandbox.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.sandbox.readinessProbe}}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.sandbox.resources | nindent 12 }}
      {{- with .Values.sandbox.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sandbox.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.sandbox.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "dify.fullname" . }}-sandbox-config
