{{- if .Values.ingress.enabled -}}
{{- $fullName := include "dify.fullname" . -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.global.enableTLS }}
  tls:
    - hosts:
      - {{ .Values.global.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
  rules:
    - host: {{ .Values.global.host | quote }}
      http:
        paths:
          - path: /console/api
            {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-api-svc
                port:
                  number: {{ .Values.api.service.port }}
              {{- else }}
              serviceName: {{ $fullName }}-api-svc
              servicePort: {{ .Values.api.service.port }}
              {{- end }}
          - path: /api
            {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-api-svc
                port:
                  number: {{ .Values.api.service.port }}
              {{- else }}
              serviceName: {{ $fullName }}-api-svc
              servicePort: {{ .Values.api.service.port }}
              {{- end }}
          - path: /v1
            {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-api-svc
                port:
                  number: {{ .Values.api.service.port }}
              {{- else }}
              serviceName: {{ $fullName }}-api-svc
              servicePort: {{ .Values.api.service.port }}
              {{- end }}
          - path: /files
            {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-api-svc
                port:
                  number: {{ .Values.api.service.port }}
              {{- else }}
              serviceName: {{ $fullName }}-api-svc
              servicePort: {{ .Values.api.service.port }}
              {{- end }}
          - path: /
            {{- if semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
              {{- else }}
              serviceName: {{ $fullName }}-frontend
              servicePort: {{ .Values.frontend.service.port }}
              {{- end }}
{{- end }}
