{{- if .Values.pluginDaemon.enabled }}
{{- if .Values.pluginDaemon.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dify.fullname" . }}-plugin-daemon-pvc
  {{- if .Values.pluginDaemon.persistence.resourcePolicy }}
  annotations:
    "helm.sh/resource-policy": {{ .Values.pluginDaemon.persistence.resourcePolicy | quote }}
  {{- end }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon
spec:
  accessModes:
    - {{ .Values.pluginDaemon.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.pluginDaemon.persistence.size | quote }}
  {{- if .Values.pluginDaemon.persistence.storageClass }}
  storageClassName: {{ .Values.pluginDaemon.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
