{{- if .Values.httpRoute.globalRateLimit.enabled }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ include "dify.fullname" . }}-global-limit
  labels:
    {{- include "dify.labels" . | nindent 4 }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: {{ include "dify.fullname" . }}
  rateLimit:
    global:
      rules:
{{- toYaml (default (list) .Values.httpRoute.globalRateLimit.rules) | nindent 8 }}
{{- end }}
