{{- if .Values.httpRoute.enabled }}
{{- $root := . }}
{{- $hostnames := (list) }}
{{- if .Values.httpRoute.ingressCompact }}
  {{- range .Values.ingress.hosts }}
    {{- if .host }}
      {{- $hostnames = append $hostnames .host }}
    {{- end }}
  {{- end }}
{{- else }}
  {{- $hostnames = default (list) .Values.httpRoute.hostnames }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.httpRoute.gatewayRef.name }}
    namespace: {{ .Values.httpRoute.gatewayRef.namespace }}
  hostnames:
  {{- range $hostnames }}
    - {{ . | quote }}
  {{- end }}
  rules:
{{- range $rule := (default (list) $root.Values.httpRoute.extraPaths) }}
  - {{ tpl (toYaml $rule) $root | nindent 4 }}
{{- end }}
  - backendRefs:
    - name: {{ include "kafka-ui.fullname" $root }}
      port: {{ $root.Values.service.port }}
{{- end }}
