{{- if .Values.appDeveloper.enabled }}
{{- if .Values.appDeveloper.viewOnly.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway-role.fullname" . }}-app-developer-view-only
  labels:
    {{- include "gateway-role.labels" . | nindent 4 }}
    {{- toYaml .Values.appDeveloper.viewOnly.labels | nindent 4 }}
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes", "tlsroutes", "gatewayclasses", "gateways", "referencegrants"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["gateway.envoyproxy.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
{{- end }}
{{- if .Values.appDeveloper.edit.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gateway-role.fullname" . }}-app-developer-edit
  labels:
    {{- include "gateway-role.labels" . | nindent 4 }}
    {{- toYaml .Values.appDeveloper.edit.labels | nindent 4 }}
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes", "tlsroutes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["gateway.envoyproxy.io"]
  resources:
  - "Backend"
  - "BackendTrafficPolicy"
  - "HTTPRouteFilter"
  - "ClientTrafficPolicy"
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
{{- end }}
