{{- if .Values.clusterAdmin.enabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "gateway-role.fullname" . }}-cluster-admin
  labels:
    {{- include "gateway-role.labels" . | nindent 4 }}
    {{- with .Values.clusterAdmin.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
rules:
  - apiGroups: ["gateway.networking.k8s.io", "gateway.envoyproxy.io"]
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
{{- end }}