apiVersion: v2
home: https://archerydms.com/
description: Archery Helm chart for Kubernetes
name: archery
version: 0.4.2
sources:
  - https://github.com/hhyo/Archery

maintainers:
  - name: AceAttorney
  - name: LeoQuote

dependencies:
  - name: redis
    version: ~15.7.1
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: redis.embedded
  - name: mysql
    version: ~8.8.20
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: mysql.embedded
  - name: goinception
    version: ~0.3.1
    repository: https://douban.github.io/charts/
    condition: goinception.embedded
